-- Execute after loading UI.lua, or use demo_independiente.lua.
local ui = _G.AstraUI or _G.Kirin
if type(ui) ~= "table" or ui.Version ~= "4.0.0" or not ui._alive then
    warn("Carga Astra UI 4.0.0 antes de ejecutar este ejemplo")
    return
end
ui:SetLayout("Compact")
local window = ui:CreateWindow({Title="ASTRA / MATCHA",Size={790,570},ToggleKey="h"})
local tab = window:AddTab({Title="Controles",Columns=2})
local status = tab:AddLabel("Tu diseno, listo para otros scripts. H muestra u oculta la ventana.")
tab:AddToggle({Title="Activado",Flag="demo.enabled",Callback=function(on)
    status:SetText(on and "Estado: activado" or "Estado: desactivado")
end})
tab:AddToggle({Title="Checkbox",Type="Checkbox",Flag="demo.checkbox"})
tab:AddSlider({Title="Intensidad",Min=0,Max=100,Step=5,Default=30,Suffix="%",Flag="demo.amount"})
tab:AddButton({Title="Notificacion",Callback=function()
    ui:Notify({Title="Astra UI",Content="Una pulsacion, una accion.",Duration=3})
end})
tab:AddDropdown({Title="Tema",Options=ui:GetThemes(),Default="Cosmos",Flag="demo.theme",Callback=function(theme)
    ui:SetTheme(theme)
end})
tab:AddKeybind({Title="Tecla de menu",Default="h",Callback=function(key) window:SetToggleKey(key) end})
tab:AddInput({Title="Nombre",Default="",Flag="demo.name",Callback=function(text) status:SetText("Hola "..text) end})
local progress=tab:AddProgressBar({Title="Progreso",Default=0.4})
tab:AddColorPicker({Title="Paleta",Style={Width=1},Flag="demo.color"})
local settings=window:AddTab({Title="Ajustes"})
settings:AddDropdown({Title="Distribucion",Options={"Compact","Default"},Default="Compact",Callback=function(name)
    window:SetLayout(name)
end})
settings:AddToggle({Title="Jardin animado",Default=true,Callback=function(on) window:SetVisualFX(on) end})
settings:AddButton({Title="Guardar configuracion",Callback=function()
    local ok,err=ui:SaveConfig("astra-demo.json")
    ui:Notify({Title="Configuracion",Content=ok and "Guardada" or tostring(err)})
end})
settings:AddButton({Title="Cargar configuracion",Callback=function()
    local ok,err=ui:LoadConfig("astra-demo.json",false)
    ui:Notify({Title="Configuracion",Content=ok and "Cargada" or tostring(err)})
end})
settings:AddButton({Title="Cerrar UI",Style="danger",Callback=function() ui:Destroy() end})
tab:Select()
